package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Victor
 */
public class InsertarVista extends javax.swing.JPanel {

    /**
     * Creates new form InsertarVista
     */
    public InsertarVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCategorias = new javax.swing.ButtonGroup();
        bgInsertar = new javax.swing.JPanel();
        pnTitulo = new javax.swing.JPanel();
        lbTitulo1 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        rbDulce = new javax.swing.JRadioButton();
        rbAcido = new javax.swing.JRadioButton();
        rbSinAzucar = new javax.swing.JRadioButton();
        lbCategoria = new javax.swing.JLabel();
        btnAgregarDulce = new javax.swing.JButton();
        lbDulce = new javax.swing.JLabel();

        bgInsertar.setBackground(new java.awt.Color(255, 250, 244));
        bgInsertar.setMaximumSize(new java.awt.Dimension(600, 450));
        bgInsertar.setMinimumSize(new java.awt.Dimension(600, 450));
        bgInsertar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTitulo.setBackground(new java.awt.Color(255, 226, 225));

        lbTitulo1.setFont(new java.awt.Font("Calisto MT", 0, 48)); // NOI18N
        lbTitulo1.setForeground(new java.awt.Color(0, 51, 51));
        lbTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo1.setText("Insertar Dulces");

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgInsertar.add(pnTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 110));

        lbNombre.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        lbNombre.setText("Ingrese el nombre del dulce");
        bgInsertar.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        txtNombre.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        txtNombre.setText("Nombre del dulce");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        bgInsertar.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, -1));

        rbDulce.setBackground(new java.awt.Color(255, 250, 244));
        btnGroupCategorias.add(rbDulce);
        rbDulce.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        rbDulce.setText("Dulce");
        bgInsertar.add(rbDulce, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        rbAcido.setBackground(new java.awt.Color(255, 250, 244));
        btnGroupCategorias.add(rbAcido);
        rbAcido.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        rbAcido.setText("Acido");
        bgInsertar.add(rbAcido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        rbSinAzucar.setBackground(new java.awt.Color(255, 250, 244));
        btnGroupCategorias.add(rbSinAzucar);
        rbSinAzucar.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        rbSinAzucar.setText("Sin azucar");
        bgInsertar.add(rbSinAzucar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        lbCategoria.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        lbCategoria.setText("Seleccione la categoria del dulce ");
        bgInsertar.add(lbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        btnAgregarDulce.setFont(new java.awt.Font("Calisto MT", 0, 18)); // NOI18N
        btnAgregarDulce.setText("Agregar dulce");
        btnAgregarDulce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDulceActionPerformed(evt);
            }
        });
        bgInsertar.add(btnAgregarDulce, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        lbDulce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dulce.png"))); // NOI18N
        bgInsertar.add(lbDulce, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 250, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarDulceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDulceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarDulceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgInsertar;
    public javax.swing.JButton btnAgregarDulce;
    public javax.swing.ButtonGroup btnGroupCategorias;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbDulce;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JPanel pnTitulo;
    public javax.swing.JRadioButton rbAcido;
    public javax.swing.JRadioButton rbDulce;
    public javax.swing.JRadioButton rbSinAzucar;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
